# Generated by Django 4.1.7 on 2023-04-25 15:55

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('media_file', models.FileField(upload_to='videos/%d', validators=[video.validators.file_size])),
            ],
        ),
    ]
