# Generated by Django 4.1.7 on 2023-05-20 01:22

from django.db import migrations, models
import video.models
import video.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_video_caption_video_height_video_new_insert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='stack',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='media_file',
            field=models.FileField(upload_to=video.models.upload_to, validators=[video.validators.file_size]),
        ),
    ]
