# Generated by Django 4.1.7 on 2023-05-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_stack_alter_video_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='video',
            name='versions',
        ),
        migrations.AddField(
            model_name='video',
            name='versions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
